# Generated by Django 5.0 on 2023-12-27 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('age', models.SmallIntegerField()),
                ('gender', models.SmallIntegerField()),
                ('context', models.TextField()),
            ],
        ),
    ]
