# Generated by Django 5.0 on 2023-12-27 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Persone',
            new_name='Person',
        ),
    ]
