# Generated by Django 5.0 on 2023-12-27 10:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0002_rename_persone_person'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='age',
        ),
    ]
