# Generated by Django 5.0 on 2023-12-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('person', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='number',
            field=models.IntegerField(max_length=12, null=True),
        ),
    ]
